/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PhoneNumber = IDL.Record({
  'city' : IDL.Text,
  'isActive' : IDL.Bool,
  'state' : IDL.Text,
  'messageCount' : IDL.Nat,
  'number' : IDL.Text,
});
export const Time = IDL.Int;
export const SMSMessage = IDL.Record({
  'senderNumber' : IDL.Text,
  'messageBody' : IDL.Text,
  'receivedTimestamp' : Time,
});

export const idlService = IDL.Service({
  'addMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deactivateNumber' : IDL.Func([IDL.Text], [], []),
  'getActiveNumbers' : IDL.Func([], [IDL.Vec(PhoneNumber)], ['query']),
  'getAllPhoneNumbers' : IDL.Func([], [IDL.Vec(PhoneNumber)], ['query']),
  'getMessagesForNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SMSMessage)],
      ['query'],
    ),
  'getNumbersByState' : IDL.Func([IDL.Text], [IDL.Vec(PhoneNumber)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PhoneNumber = IDL.Record({
    'city' : IDL.Text,
    'isActive' : IDL.Bool,
    'state' : IDL.Text,
    'messageCount' : IDL.Nat,
    'number' : IDL.Text,
  });
  const Time = IDL.Int;
  const SMSMessage = IDL.Record({
    'senderNumber' : IDL.Text,
    'messageBody' : IDL.Text,
    'receivedTimestamp' : Time,
  });
  
  return IDL.Service({
    'addMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deactivateNumber' : IDL.Func([IDL.Text], [], []),
    'getActiveNumbers' : IDL.Func([], [IDL.Vec(PhoneNumber)], ['query']),
    'getAllPhoneNumbers' : IDL.Func([], [IDL.Vec(PhoneNumber)], ['query']),
    'getMessagesForNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SMSMessage)],
        ['query'],
      ),
    'getNumbersByState' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PhoneNumber)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };